### ISSUE TITLE
Coordinate System does not match SpriteKit

### ISSUE THREAD

**Issue by riklowe** [TomLinthwaite/SKTilemap#12]
By default - Tiled coordinate system puts (0,0) in the top left
By default - SpriteKit coordinate system puts (0,0) in the bottom left 

This is resulting in Y values that start at 0 and reduce to -screen size
To correct this - I believe you can add Screen Height to the y position when tiles are loaded.

In SKTilemapLayer -  fun tilePositionAtCoord

change

```
    case .Orthogonal:

        position = CGPoint(x: x * Int(tileSize.width) + Int(tileAnchorPoint.x * tileSize.width),
                           y: y * Int(-tileSize.height) - Int(tileSize.height - tileAnchorPoint.y * tileSize.height))
```

to

```
    case .Orthogonal:

        let tmpMapSize = Int(tilemap.size.height * tileSize.height)
        let tmpYpos = y * Int(-tileSize.height) - Int(tileSize.height - tileAnchorPoint.y * tileSize.height)

        position = CGPoint(x: x * Int(tileSize.width) + Int(tileAnchorPoint.x * tileSize.width),
                           y: tmpMapSize + tmpYpos)
```

Testing seems to produce the correct results with Y values now starting at 0 in the bottom of the screen
Additionally this change did not seem to produce any other side effects (but will require more testing)

Let me know what you think

Rgds
Richard

**Comment by riklowe** [comment]
Note : may need to do similar for Isometric maps !

```
    case .Isometric:

        position = CGPoint(x: (x - y) * Int(tileSizeHalved.width) - Int(tileSizeHalved.width - tileAnchorPoint.x * tileSize.width),
                           y: (x + y) * Int(-tileSizeHalved.height) - Int(tileSize.height - tileAnchorPoint.y * tileSize.height))
```

**Comment by riklowe** [comment]
Similarly - I see that in the object group processing you have tried to take account for the difference in Tiled and SpriteKit coordinates.

However - whilst you have correctly move the object from Tiled to SpriteKit coordinates - you have still left the object anchor at top left - not bottom left.

In SKTilemapObject.swift , class SKTilemapObject you have

```
    self.position = CGPoint(x: Int(x)!, y: Int((objectGroup.tilemap.size.height - 1) * objectGroup.tilemap.tileSize.height) - Int(y)!)

    if let width = attributes["width"] where (Int(width)) != nil,
        let height = attributes["height"] where (Int(height) != nil) {

        size = CGSize(width: Int(width)!, height: Int(height)!)
    } else {
        size = CGSizeZero
    }
```

I believe it should be - 

```
    if let width = attributes["width"] where (Int(width)) != nil,
        let height = attributes["height"] where (Int(height) != nil) {

        size = CGSize(width: Int(width)!, height: Int(height)!)
    } else {
        size = CGSizeZero
    }

    self.position = CGPoint(x: Int(x)!, y: Int((objectGroup.tilemap.size.height) * objectGroup.tilemap.tileSize.height) - Int(y)! - Int(self.size.height))
```

This corrects the objects anchor point

**Comment by TomLinthwaite** [comment]
I'll have to have a proper look at this when I get home. I don't really want to follow tileds coordinate system because for everything else not related to the map in your game code you'll stick to sprite kits cooed system. Even if you draw the Sprite below you still have to position what ever nose your position in the opposite y. If you have to position something on a tile just use the tiles position instead of hard coding. Like I said I'll have a look when I get back from work but I'm pretty sure I want to stick to how Sprite kit does it. If you want to change the anchor point of the tiles look at the Orientation emus and change it there for what ever orientation your using.

**Comment by riklowe** [comment]
Note : The code I have provided uses SpriteKits co-ord system.

**Comment by TomLinthwaite** [comment]
OK so I've had a mess about with the objects and stuff and decided on changing a few things. I've set up a change log at https://github.com/TomLinthwaite/SKTilemap/blob/master/CHANGELOG.md which details what I've done.
Let me know if this works for you. 

About changing the positions of the tiles in the layer I used your code instead and it causes some issues with the tile clipping and camera bounds for some reason. I'm not sure I want to change it as in reality the position of the tiles shouldn't matter. And if you really need to use a tiles position you can always get it through one of the `tileAt...' functions then using tile.position. This is only useful if you're adding nodes directly to that layer, which I don't think is a good idea. So instead convert the position to the node you want. for example:

`myNode.position = layer.convertPoint(tile.position, toNode: worldNode)
worldNode.addChild(myNode)`

Your node will now be at the correct place, accounting for anchor points of the tile and your node. 
I still might look into this further since I think you are correct and it would just make more sense to have it in the positive y axis. I just want to fix the tile clipping problem first :P

**Comment by riklowe** [comment]
OK no problem. Thanks

**Comment by DanieleBarone** [comment]
Hello Tom, 
I have noticed that after the above discussion, the **position** properties has been deleted.

I am trying to use the **postionOnLayer** function but it does not provide the expected result (see an example at the bottom). Worst case scenario, I can use the below function to extend the library in my code, but I was wondering if something similar can be included directly in your project. The main reason is that in the tile map I have an object layer that defines placeholders for different objects. In sprite kit, I parse the object layer and depending on the type of the object placeholder I use a corresponding class to create a SKNode (e.g., finish level) or SKSpriteNode (e.g. an enemy).

```
  func calculatePosition(object:SKTilemapObject) -> CGPoint {

    let x = (object.coord.x * tileMap.tileSize.width)
    let y = (abs((object.coord.y - tileMap.size.height+1)) * tileMap.tileSize.height)

    return CGPointMake(x,y)

  }
```

In the example below, I have at 12x12 tile map, each tile has 32x32 size.
In TMX coordinate, I have a start placeholder at 2x10 coord. When converting to Sprite Kit coordinate i am expecting a (x=64.0, y=32.0)  position (see function above), but using the **postionOnLayer** function I got a (80.0, -336.0) position.

Thank you for any support you may provide.

```
Tilemap: test (1.0), Size: (12.0, 12.0), TileSize: (32.0, 32.0), Orientation: Orthogonal
Properties: [:]

Tileset: border, firstGID: 1, TileSize: (32.0, 32.0), TileOffset: (0.0, 0.0), Source: border.bmp, Margin: 0, Spacing: 0
Properties: [:]
TileData: 1, Source: , Properties: ["physicBodyShape": "square"]

SKTileLayer: Optional("GroundLayer"), Offset: (0.0, 0.0), Opacity: 1.0, Visible: true
Properties: [:]

SKTilemapObjectGroup: Enemy
Properties: [:]

SKTilemapObjectGroup: Object
Properties: [:]

SKTilemapObject: 1, Name: Start, Type: Start, Raw Position: (64.0, 320.0), Size: (32.0, 32.0)
Properties: [:]

SKTilemap: Loaded tilemap 'test' in 0.0582969784736633 seconds.
[TileLayer] Loaded Map test
[TileLayer] Size [12.0, 12.0]
Object coor:2.0, 10.0 
Object position (SKTileMap) :80.0, -336.0 
Object position (Expected):64.0, 32.0 
```

**Comment by TomLinthwaite** [comment]
But if you place an object/Sprite/node at that location it appears at 0,2 on the map right?

**Comment by DanieleBarone** [comment]
Hello Tom,
I am not sure I got your question right?

to place an object/sprite/node at a specific location I need to have proper x,y. I am trying to calculate them using the **postionOnLayer** function since the **position** property does not longer exist. The position I am looking for should refer to the Sprite Kit coordinate system. In the meantime, I am using the below function to calculate such a position by relying on the coord property:

```
  func calculatePosition(object:SKTilemapObject) -> CGPoint {

    let x = (object.coord.x * tileMap.tileSize.width)
    let y = (abs((object.coord.y - tileMap.size.height+1)) * tileMap.tileSize.height)

    return CGPointMake(x,y)

  }

```

if I use the (expected) position calculated with the above (see the example in previous post), my object/sprite/node is positioned correctly to TMX coord 2,10. If I am using the position calculated with **postionOnLayer** function, object/sprite/node  is way outside the map.

my goal:
Have a function/property that returns position (x,y) in Sprite Kit system coordinate for any object in an object layer with an associated TMX coord (xTMX, yTMX).

position.x = fun(TMXCoord.x)
position.y = fun(TMXCoord.y)

The function above can do the trick, but it would be nice to have it part of the library, since maybe of a generic use, I guess.

Worst case scenario I will extend the library in my code :)
Hope this helps to clarify the request, and no worries if you think that it should not be part of the library,'
Thank you!!

**Comment by TomLinthwaite** [comment]
Ok I think I understand what's going on. The position returned from the current function is the tiles position in its parents coordinate system (the layer you specified when getting the position). So if you were adding a node to that position/coord you would add it as a child of that layer. This position is guaranteed to be correct. How ever you probably don't want to add a your noses directly to that layer.

The problem with your method is that it works if the layers offset is 0,0, the tiles anchor points are at default, the object layers offset is at 0,0 and the map alignment is set a certain way. If you change any of those things the position from your function will be wrong. 

The object class does not know about all of that information so therefore there is no guaranteed way to get its correct position this way.

So how to get the position you want?

First get the object position using positionInLayer. Now you know that the position returned is correct as that is the tiles position for this objects coord. Now you simply convert this position to what ever node space you want for example:   

```
Let tilePosition = object.positionInLayer(layer)
Let wolrdPosition = worldNode.convertPoint(tilePosition, fromNode: layer)
Let scenePosition = scene?.convertPosition(worldPosition, fromNode: worldNode)
```

I assume your object is either added to the world node or scene so one of them positions should be correct. The reason I can't add a function like this directly to the library is because everyone's scene hierarchy might've different. That's why I thought it would be a good idea to have a guaranteed position to start from.

Does this make sense? Let me know if doing it this way works.
