### ISSUE TITLE
Cropped Nodes

### ISSUE THREAD

**Issue by riklowe** [TomLinthwaite/SKTilemap#2]
Hi Tom

Great work so far on this - it looks and works really well.
Do you have any plans to support cropping ?
I have tile maps that are 50 \* 500 - which creates a lot of objects and requires some form of cropping to keep frame rates at a reasonable level (Note : JSTileMap has similar built in)

**Comment by TomLinthwaite** [comment]
Hi, by "creating a lot of objects" i assume you mean tiles (nodes) and not handling object logic you may have created from the object layer?
I've implemented something similar before by cropping tiles that are not visible within the current view or custom "bounds" so I don't see why I can't again. I'll make it the next thing I work on.
Last time I think I wrote code like this I had the camera handle it, but I don't want the camera to have control of this as it's just there as an example so I think I will implement it within the main tilemap class itself and just worry about cropping to the size of the scene. Hope that answers your question.

**Comment by TomLinthwaite** [comment]
I've done some quick test with a large 256x256 tilemap and it seems Sprite Kit is clever enough the cull the tiles outside the view anyway. You can see that yourself by seeing how many nodes are drawn in the debug text, the fps also increases. For now I might put this feature off as it does seem to be mainly handled by the camera with custom bounds.

**Comment by riklowe** [comment]
Hi Tom

I just extended your tilemap_isometric map to 50 \* 500 - and filled the map with grass/sand and water tiles.  Running on my device (iPhone 6  plus) it is showing 18860 nodes and a fps of 12.6 -  so it would appear sprite kit does not perform the culling.

**Comment by TomLinthwaite** [comment]
Weird. Are you zoomed all the way out? 

Regardless I will do the culling myself anyway but just for the size of the view for now. I think just making the tiles hidden will be enough as its recommended not to keep add/removing children all the time.

**Comment by riklowe** [comment]
no not zoomed out - just took your sample code and  extended the tiles

**Comment by TomLinthwaite** [comment]
I've just uploaded a way to clip tiles but its not perfect. It still loops through all the tiles of  map when deciding which tiles need to be clipped. This loop can be significantly smaller but maths is evading me at the moment when it comes to iso maps, I can get it working on ortho maps but im gonna leave it for a bit and come back in a couple hours.

**Comment by riklowe** [comment]
Thanks I will check it out

**Comment by TomLinthwaite** [comment]
Ive actually had a moment of clarity in my sleep last night and should be able to get this working a lot smoother. I'll do it when I get in from work

**Comment by riklowe** [comment]
Thanks - I'll check it out when you post

**Comment by TomLinthwaite** [comment]
OK I've just updated the code. I've commented it as best I can because I had to add a new call to the tilemap to enable tile clipping. Have a look and tell me what you think so I can close the issue :)

**Comment by riklowe** [comment]
The culling is working - I see in the example the map is 500 \* 50 - and the node count is only 185 (when zoomed in) but the frame rate is still quite low (35 fps). As you stated in the comments - ideally the tilemap itself should know when it needs to update rather than have to call the function each time the zoom changes.

**Comment by TomLinthwaite** [comment]
I'm afraid that's out of the scope of SKTilemap. The camera is there as an example. You should be able to easily implement a call to crop the tiles when the camera zooms. I just don't want to do that as every games different and it has no place in the core functionality of the project. 

I can think of two more improvements to the existing code. 

One where the cropping never happens if the same tile is still in the top left corner when the loop starts (as the cropping outcome will be the same as before).

And Two not to bother cropping At all when the whole map is in view. As it's just a waste of time.

Other than that the loops as tight as it can be I believe as its only concerned with the tiles within the bounds and no longer looping through all 500x50 tiles. If you really need to have all those tiles it may be better the split the map itself and load it in chunks. But I feel this is out of the scope of the project to as like I say every games different and there's no one size fits all solution. If you have a link for that JSTilemap code where this runs better please let me see it.

**Comment by riklowe** [comment]
here is link. https://github.com/slycrel/JSTileMap

**Comment by TomLinthwaite** [comment]
There is no optimisation for displaying a large number of nodes in that code at all? Are you saying your map runs fine in JSTilemap?

**Comment by riklowe** [comment]
I have a 50 \* 500 orthogonal map - running on the device (iPhone 6 plus) I see 145 nodes and fps 61.2
I think the optimisation is in the showTilesInVisibleRect function in JSTileMap.m.

**Comment by TomLinthwaite** [comment]
I can't find it. I'm looking here: https://github.com/slycrel/JSTileMap/blob/master/TMXMapSample/JSTileMap.m

I am on my phone so it's a little difficult. Do you have a link I'm interested in the code :)

**Comment by riklowe** [comment]
not sure what is happening with that git hub repository - the link you have sent back looks right - but appears to be an older version of the file.
if you download the zip - and open up the JSTileMap.M file - you can find the code on line 611

**Comment by TomLinthwaite** [comment]
OK so I downloaded the zip but there is still no function like you describe or any tile culling of any sort. But I ran the map (50x500) using it an you're right it does run faster. So after thinking about it for a bit and looking over at Apples best practices it seems that having 25000 nodes in memory is probably not a good thing. This is because even though they get hidden, Sprite Kit still works through every node added to the scene each frame to update any logic. I did some profiling and found I didn't have 25000 nodes, I had 50000. This is because the Tile is a node which in turn has a SpriteNode as a child. So I removed the sprite from the Tile and made the Tile a SpriteNode itself. Which of course halves the amount of nodes added to the scene and increases performance to the same as JSTilemap.

I'm now questioning the use of cropping the tiles, I'm not sure it's entirely worth it as like I said before Sprite Kit does already know what is and isn't visible and it just adds another loop per frame for the tilemap to run through. I'll leave it in for now though and remove it later if its an issue.

Supporting large maps is pretty cool, and I am thinking about a system where portions of the maps are loaded in chunks. This would be good for games with unlimited maps. But it's not top priority and pretty game specific.

Anyway have a play with the new build and let me know if it's ok. Try disabling the cropping and let me know if that makes things worse or better.

**Comment by TomLinthwaite** [comment]
Actually I just tested again with the tile clipping and there is defiantly and improvement with it on. So it stays :P

**Comment by riklowe** [comment]
Yes - That will make a difference !!!  
I will check it out tonight and let you know.
Thanks

**Comment by riklowe** [comment]
This is a massive improvement. In fact, as you said it works at 60fps even when cropping is disabled 
So I think this issue can be closed. Great job. Thanks.
I'll keep playing and advise if I find anything else.

**Comment by TomLinthwaite** [comment]
Thanks glad to finally get this sorted :) and yes please do!
