### ISSUE TITLE
TileMap aligned with the bottom left corner

### ISSUE THREAD

**Issue by DanieleBarone** [TomLinthwaite/SKTilemap#3]
Hello Tom,
     brilliant job! I was looking for a library like yours for a long time.

I was just wondering if you are planning to have an option that allows the TileMap to be aligned to the bottom left corner of the screen. Currently, I see that the map has been centred in the middle of the screen.
Thank you
Daniele

**Comment by TomLinthwaite** [comment]
Hi and thank you.

I can have a look at this problem tonight it shouldn't be a problem. One of the main reasons I kept it like this is because it made sense across all orientations. It also just helped when working with cameras as they keep the scenes origin at the centre of the screen. 

I think I'll add a computed property that can be changed like an anchor point so you can have the map aligned how you want.

**Comment by TomLinthwaite** [comment]
I've added a new property to the tilemap. I've documented the code in the game scene so you can experiment. But to get what you want you'll have to call:

```
tilemap.alignment = CGPointZero
```

This will put the left/bottom most edge of the tilemap at the 0,0 position in the scene so you only have to deal with positive axis :)

**Comment by DanieleBarone** [comment]
Sincerely thank you, Tom!! I did a quick test and it seems working like a charm, I will try on my original project!
