### ISSUE TITLE
Incorrect gid returned

### ISSUE THREAD

**Issue by riklowe** [TomLinthwaite/SKTilemap#9]
Hi Tom

Are you aware that the "gid" being returned by  gid = node.tileData.id
is 1 higher than the tile ID shown in "Tiled" ?

Note : JSTileMap had same issue - so I suspect it may be the way Tiled is exporting the data

Is this something you can correct ?

**Comment by riklowe** [comment]
clearly a simple solution to this problem is to add this into my code -

gid = node.tileData.id - 1

but I am not sure what impact having the wrong gid is having in the rest of the library

**Comment by TomLinthwaite** [comment]
There is a reason for this and you can see it yourself when you look at the id's for your tiles in Tiled. 
When Tiled saves its map data it uses 0 to indicate there is no tile at that location. It also uses 0 as the first GID in a tileset. If you have a tileset made up from a collection, adding/removing a tile will not update GIDs within the tileset. For example I have a tileset containing 3 images, GIDs (0, 1, 2). Removing the last image then adding another gives me the GIDs (0, 1, 3). I'm not entirely sure why it happens this way. It also gets more confusing when using multiple tilesets.

Anyway, the actual GID you end up with can never be zero because that indicates no tile. But it is generated by adding the Tileset.firstGID property to it's actual ID. For example when I load the map and I find tileGid 0 I set that data to firstGid+tileID. 

Sorry for the long response, I've made an update to TileData to give the rawID (the one you see in tiled). I wont make any other functions work with the rawID however as like I said. If you have multiple tilesets IDs will conflict and it causes confusion. I can see why it might make things easier though just to have it.

**Comment by riklowe** [comment]
Thanks - I suspected this was more of a Tiled issue.
Will check out your solution
